-- MySQL Script generated by MySQL Workbench
-- Sun Feb  8 23:50:06 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Compras
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Compras
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Compras` DEFAULT CHARACTER SET utf8 ;
USE `Compras` ;

-- -----------------------------------------------------
-- Table `Compras`.`Login`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Compras`.`Login` ;

CREATE TABLE IF NOT EXISTS `Compras`.`Login` (
  `idLogin` INT NOT NULL AUTO_INCREMENT,
  `user` VARCHAR(45) NULL,
  `pass` VARCHAR(45) NULL,
  PRIMARY KEY (`idLogin`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Compras`.`Productos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Compras`.`Productos` ;

CREATE TABLE IF NOT EXISTS `Compras`.`Productos` (
  `idProductos` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  `descripcion` VARCHAR(45) NULL,
  `valor` INT NULL,
  `imagene` BLOB NULL,
  PRIMARY KEY (`idProductos`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Compras`.`Compras`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Compras`.`Compras` ;

CREATE TABLE IF NOT EXISTS `Compras`.`Compras` (
  `idCompras` INT NOT NULL AUTO_INCREMENT,
  `Login_idLogin` INT NOT NULL,
  `Productos_idProductos` INT NOT NULL,
  PRIMARY KEY (`idCompras`, `Login_idLogin`, `Productos_idProductos`))
ENGINE = InnoDB;

CREATE INDEX `fk_Compras_Login_idx` ON `Compras`.`Compras` (`Login_idLogin` ASC) VISIBLE;

CREATE INDEX `fk_Compras_Productos1_idx` ON `Compras`.`Compras` (`Productos_idProductos` ASC) VISIBLE;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `Compras`.`Login`
-- -----------------------------------------------------
START TRANSACTION;
USE `Compras`;
INSERT INTO `Compras`.`Login` (`idLogin`, `user`, `pass`) VALUES (1, 'marchelo', '1234');
INSERT INTO `Compras`.`Login` (`idLogin`, `user`, `pass`) VALUES (2, 'jose', '1234');
INSERT INTO `Compras`.`Login` (`idLogin`, `user`, `pass`) VALUES (3, 'maria', '1234');
INSERT INTO `Compras`.`Login` (`idLogin`, `user`, `pass`) VALUES (4, 'jorge', '1234');

COMMIT;


-- -----------------------------------------------------
-- Data for table `Compras`.`Productos`
-- -----------------------------------------------------
START TRANSACTION;
USE `Compras`;
INSERT INTO `Compras`.`Productos` (`idProductos`, `nombre`, `descripcion`, `valor`, `imagene`) VALUES (1, 'completo', 'tomate,plata,mayo', 1000, NULL);
INSERT INTO `Compras`.`Productos` (`idProductos`, `nombre`, `descripcion`, `valor`, `imagene`) VALUES (2, 'lomito', 'palta,tomate,mayo', 1500, NULL);
INSERT INTO `Compras`.`Productos` (`idProductos`, `nombre`, `descripcion`, `valor`, `imagene`) VALUES (3, 'papas fritas', 'papas,sal', 500, NULL);
INSERT INTO `Compras`.`Productos` (`idProductos`, `nombre`, `descripcion`, `valor`, `imagene`) VALUES (4, 'sushi', 'palta,arroz,pollo', 2000, NULL);

COMMIT;

